cambio detect folder

diff --git a/.github/workflows/deploy_regular.yaml b/.github/workflows/deploy_regular.yaml
--- a/.github/workflows/deploy_regular.yaml
+++ b/.github/workflows/deploy_regular.yaml
@@ -27,23 +27,29 @@ jobs:
           fetch-depth: 0  # Descarga todo el historial de commits.
 
       # Paso 2: Detectar carpeta basada en el nombre de la rama
-      - name: Detect Directory from Branch Name
+      - name: Detect Directory from Pull Request Branch
         id: detect-dir
         run: |
           # Extraer el path completo después de "tf/"
-          DIR_NAME=$(echo "${{ github.ref_name }}" | sed 's#^tf/##')
+          if [[ "${{ github.event.pull_request.head.ref }}" == tf/* ]]; then
+            DIR_NAME=$(echo "${{ github.event.pull_request.head.ref }}" | sed 's#^tf/##')
 
-          # Buscar el directorio exacto en el repositorio
-          DIR=$(find . -type d -path "./$DIR_NAME" -print -quit)
+            # Buscar el directorio exacto en el repositorio
+            DIR=$(find . -type d -path "./$DIR_NAME" -print -quit)
 
-          # Validar si se encontró el directorio
-          if [ -z "$DIR" ]; then
-            echo "Error: No directory matching '${DIR_NAME}' found!"
-            exit 1
+            # Validar si se encontró el directorio
+            if [ -z "$DIR" ]; then
+              echo "Error: No directory matching '${DIR_NAME}' found!"
+              exit 1
+            else
+              echo "Detected directory: $DIR"
+              echo "directory=$DIR" >> $GITHUB_ENV
+            fi
           else
-            echo "Detected directory: $DIR"
-            echo "directory=$DIR" >> $GITHUB_ENV
+            echo "Branch name '${{ github.event.pull_request.head.ref }}' does not follow the 'tf/' convention. Skipping."
+            exit 0
           fi
+
       
       # Paso 3: Verificar y listar contenido del directorio
       - name: Check and List Directory
